### ISSUE TITLE
[BUG] AWK is missing in samba image but it is used in entrypoint

### ISSUE THREAD

**Issue by claudio4** [openSUSE/container-images#11]
## The problem
The SAMBA container image uses `awk` in its `entrpypoint.sh` to parse the the `USER` and `SHARE` environmental variables, but AWK it's not installed installed. This prints an error in stderr and results in said variables not being properly used. but does no prevent the rest of the script from running in typical bash fashion, so it can pass unnoticed.

Example container output.
```
/entrypoint.sh: line 182: awk: command not found
/entrypoint.sh: line 186: awk: command not found
smbd version 4.19.4-git.339.acf1ccaa020SUSE-oS16.9-x86_64 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
```
## How to replicate
Nothing special just run the samba container. `podman run --rm registry.opensuse.org/opensuse/samba`

## Proposed solution
Install awk with Zypper in [line 22 of the Dockerfile](https://github.com/openSUSE/container-images/blob/1d8e0ec58e629f2558cd57b48bbda578d96fce2f/samba/Dockerfile#L22).

The containers seems to be using gnu core utils, so `gawk` might be more appropriate, but even `busybox-gawk` seems to be lighter. The former will add 1.3 Mib to the image while the first will add 4.8 MiB, per zypper reporting.

## How to prevent this kind of problem in the future
It might be wise to add a `set -e` to the start of the `entrypoint,sh` to prevent this kind of error from going unnoticed.

**Comment by thkukuk** [comment]
Thanks, should be fixed now.
