### ISSUE TITLE
samba-ad-dc: add ldb-tools to container

### ISSUE THREAD

**Issue by fatmalama** [openSUSE/container-images#9]
needed ldbsearch today but it isn't included. I think it's fair to assume any of the ldb-tools could be needed by anyone

**Comment by fatmalama** [comment]
adding that ldb-tools are needed to make an offline backup

**Comment by dmulder** [comment]
It's a 1 line change. You're welcome to submit your own PRs to this repo. I'll patch this one though.

**Comment by fatmalama** [comment]
I found out tdb-tools is also required. I've submitted PR #12 and successfully done an offline backup now
